import nationQuery from './endpoints/NationQuery';
import allianceQuery from './endpoints/AllianceQuery';
import tradePricesQuery from './endpoints/TradePricesQuery';
import warQuery from './endpoints/WarQuery';
import tradeQuery from './endpoints/TradeQuery';
import treasureQuery from './endpoints/TreasureQuery';
import colorQuery from './endpoints/ColorQuery';
import bankRecordsQuery from './endpoints/BankRecordsQuery';
import bountyQuery from './endpoints/BountyQuery';
import cityQuery from './endpoints/CityQuery';
import embargoQuery from './endpoints/EmbargoQuery';
import treasureTradeQuery from './endpoints/TreasureTradeQuery';
import ApiKeyDetailsQuery from './endpoints/ApiKeyDetailsQuery';
import treatyQuery from './endpoints/TreatyQuery';
import BBGameQuery from './endpoints/Baseball/BBGameQuery';
import BBPlayerQuery from './endpoints/Baseball/BBPlayerQuery';
import BBTeamQuery from './endpoints/Baseball/BBTeamQuery';
import bankDepositMutation from './endpoints/mutations/BankDepositMutation';
import bankWithdrawMutation from './endpoints/mutations/BankWithdrawMutation';
import assignTaxBracketMutation from './endpoints/mutations/AssignTaxBracketMutation';
import editTaxBracketMutation from './endpoints/mutations/EditTaxBracketMutation';
import createTaxBracketMutation from './endpoints/mutations/CreateTaxBracketMutation';
import deleteTaxBracketMutation from './endpoints/mutations/DeleteTaxBracketMutation';
import proposeTreatyMutation from './endpoints/mutations/ProposeTreatyMutation';
import approveTreatyMutation from './endpoints/mutations/ApproveTreatyMutation';
import cancelTreatyMutation from './endpoints/mutations/CancelTreatyMutation';
import subscribe from './subscriptions/index';

export default class PnwKitAPI {
  apiKeyDetailsQuery = ApiKeyDetailsQuery;
  nationQuery = nationQuery;
  allianceQuery = allianceQuery;
  tradePricesQuery = tradePricesQuery;
  warQuery = warQuery;
  tradeQuery = tradeQuery;
  treasureQuery = treasureQuery;
  colorQuery = colorQuery;
  bankRecordsQuery = bankRecordsQuery;
  bountyQuery = bountyQuery;
  cityQuery = cityQuery;
  embargoQuery = embargoQuery;
  treasureTradeQuery = treasureTradeQuery;
  treatyQuery = treatyQuery;
  BBGameQuery = BBGameQuery;
  BBPlayerQuery = BBPlayerQuery;
  BBTeamQuery = BBTeamQuery;
  bankDepositMutation = bankDepositMutation;
  bankWithdrawMutation = bankWithdrawMutation;
  assignTaxBracketMutation = assignTaxBracketMutation;
  editTaxBracketMutation = editTaxBracketMutation;
  createTaxBracketMutation = createTaxBracketMutation;
  deleteTaxBracketMutation = deleteTaxBracketMutation;
  proposeTreatyMutation = proposeTreatyMutation;
  approveTreatyMutation = approveTreatyMutation;
  cancelTreatyMutation = cancelTreatyMutation;
  subscribe = subscribe;
}
